[package]
name = "fltk-derive"
version = "1.2.6"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Rust bindings for the FLTK GUI library"
repository = "https://github.com/fltk-rs/fltk-rs"
keywords = ["gui", "bindings", "graphics"]
license = "MIT"